name: release
on:
  schedule:
    - cron: '5 5 * * *'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  ZIG_VERSION: 0.13.0
  GLIBC_VERSION: 2.17
  BIN_DIR: ${{ github.workspace }}/bin

# Build with zig cc so we can target glibc 2.17, so we have broader compatibility
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        runner: [ ubuntu-22.04, ubuntu-22.04-arm ]
        variant: [ puc, luajit ]
        include:
          - { runner: ubuntu-22.04,    arch: x86_64 }
          - { runner: ubuntu-22.04-arm, arch: arm64 }

    runs-on: ${{ matrix.runner }}
    env:
      LDAI_NO_APPSTREAM: 1 # skip checking (broken) AppStream metadata for issues
    steps:
      - if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly'
        uses: actions/checkout@v7
        with:
          repository: 'neovim/neovim'
          ref: ${{ github.event.inputs.tag_name }}
          fetch-depth: 0

      - if: github.event_name == 'schedule' || github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name == 'nightly')
        uses: actions/checkout@v7
        with:
          repository: 'neovim/neovim'
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - run: sudo apt-get install -y fuse libfuse2 # For linuxdeploy.

      - name: Add "$BIN_DIR" to path
        run: |
          mkdir -p "$BIN_DIR"
          echo "$BIN_DIR" >> $GITHUB_PATH

      - name: Install Zig
        run: |
          curl -O https://ziglang.org/download/$ZIG_VERSION/zig-linux-$(arch)-$ZIG_VERSION.tar.xz
          tar -xf zig-linux-$(arch)-$ZIG_VERSION.tar.xz
          rm -rf zig-linux-$(arch)-$ZIG_VERSION.tar.xz
          ln -s $(pwd)/zig-linux-$(arch)-$ZIG_VERSION/zig $BIN_DIR/zig

          # Include -lunwind so luajit can be linked
          # Include -g0 to strip debug info by default.
          #   Note: Cmake should override this for debug builds by appending -g
          echo 'exec zig cc -target $(arch)-linux-gnu.${GLIBC_VERSION} -lunwind -g0 "$@"' > $BIN_DIR/zigcc
          chmod +x $BIN_DIR/zigcc

      - if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name != 'nightly')
        run: |
          echo 'CMAKE_BUILD_TYPE=Release' >> $GITHUB_ENV
          echo 'APPIMAGE_TAG=latest' >> $GITHUB_ENV

      - if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag_name == 'nightly')
        run: |
          echo 'CMAKE_BUILD_TYPE=RelWithDebInfo' >> $GITHUB_ENV
          echo 'APPIMAGE_TAG=nightly' >> $GITHUB_ENV

      - name: Build neovim (${{ matrix.variant }})
        env: { CC: zigcc }
        run: |
          case "${{ matrix.variant }}" in
            puc)
              DEPS_CMAKE_FLAGS="-DUSE_BUNDLED_LUA=ON" \
              CMAKE_EXTRA_FLAGS="-DPREFER_LUA=ON -DCMAKE_LIBRARY_PATH=/usr/lib/$(uname -m)-linux-gnu -DCPACK_PACKAGE_FILE_NAME=nvim-linux-${{ matrix.arch }}-puc" \
              OUTPUT=nvim-linux-${{ matrix.arch }}-puc.appimage \
                ./scripts/genappimage.sh ${APPIMAGE_TAG}
              ;;
            luajit)
              ./scripts/genappimage.sh ${APPIMAGE_TAG}
              ;;
          esac

      - name: Package tar.gz + deb
        run: cpack --config build/CPackConfig.cmake

      - name: Flatten appimage
        run: mv "build/bin/nvim-linux-${{ matrix.arch }}${{ matrix.variant == 'puc' && '-puc' || '' }}.appimage"* build/ || true

      - uses: actions/upload-artifact@v7
        with:
          name: nvim-linux-${{ matrix.arch }}${{ matrix.variant == 'puc' && '-puc' || '' }}
          path: |
            build/nvim-linux-${{ matrix.arch }}${{ matrix.variant == 'puc' && '-puc' || '' }}.tar.gz
            build/nvim-linux-${{ matrix.arch }}${{ matrix.variant == 'puc' && '-puc' || '' }}.deb
            build/nvim-linux-${{ matrix.arch }}${{ matrix.variant == 'puc' && '-puc' || '' }}.appimage
            build/nvim-linux-${{ matrix.arch }}${{ matrix.variant == 'puc' && '-puc' || '' }}.appimage.zsync
          retention-days: 1

  publish:
    needs: [linux]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      # Must perform checkout first, since it deletes the target directory
      # before running, and would therefore delete the downloaded artifacts
      - uses: actions/checkout@v7

      - uses: actions/download-artifact@v8

      - name: Get version from build
        run: |
          mkdir -p version
          tar -xzf nvim-linux-x86_64/nvim-linux-x86_64.tar.gz -C version
          {
            echo "NVIM_VERSION=$(./version/nvim-linux-x86_64/bin/nvim --version | head -n 1 | awk '{print $2}')"
            echo "LUAJIT_VERSION=$(./version/nvim-linux-x86_64/bin/nvim --version | sed -n '3p' | awk '{print $NF}')"
          } >> "$GITHUB_ENV"
          if [ -f nvim-linux-x86_64-puc/nvim-linux-x86_64-puc.tar.gz ]; then
            tar -xzf nvim-linux-x86_64-puc/nvim-linux-x86_64-puc.tar.gz -C version
            echo "LUA_VERSION=$(./version/nvim-linux-x86_64-puc/bin/nvim --version | sed -n '3p' | awk '{print $NF}')" >> "$GITHUB_ENV"
          else
            echo 'LUA_VERSION=5.1' >> "$GITHUB_ENV"
          fi

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gettext-base

      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV

      - if: github.event_name == 'schedule'
        run: echo 'TAG_NAME=nightly' >> $GITHUB_ENV

      - if: github.event_name == 'push'
        run: |
          TAG_NAME=${{ github.ref }}
          echo "TAG_NAME=${TAG_NAME#refs/tags/}" >> $GITHUB_ENV

      - name: Publish release
        env:
          DEBUG: api
        run: |
          if [ "$TAG_NAME" == "nightly" ]; then
            SUBJECT='Nvim development (prerelease) build'
            PRERELEASE='--prerelease'
          else
            SUBJECT='Nvim release build'
            PRERELEASE=
          fi
          envsubst '${NVIM_VERSION} ${LUAJIT_VERSION} ${LUA_VERSION}' < "$GITHUB_WORKSPACE/.github/workflows/notes.md" > "$RUNNER_TEMP/notes.md"

          if [ "$TAG_NAME" == "nightly" ]; then
            git push origin :nightly || true
          else
            gh release delete stable --yes || true
            git push origin :stable || true
            gh release create stable \
              --notes-file "$RUNNER_TEMP/notes.md" \
              --title "$SUBJECT" \
              --target $GITHUB_SHA \
              nvim-linux-x86_64/* nvim-linux-arm64/* nvim-linux-x86_64-puc/* nvim-linux-arm64-puc/*
          fi

          gh release delete $TAG_NAME --yes || true
          gh release create $TAG_NAME $PRERELEASE \
              --notes-file "$RUNNER_TEMP/notes.md" \
              --title "$SUBJECT" \
              --target $GITHUB_SHA \
              nvim-linux-x86_64/* nvim-linux-arm64/* nvim-linux-x86_64-puc/* nvim-linux-arm64-puc/*
